version: "3"
services:
  node-exporter:
    image: prom/node-exporter
    hostname: prometheus-node-exporter
    container_name: prometheus-node-exporter
    networks:
      - prometheus-node-exporter
    ports:
      - 9100:9100
networks:
  prometheus-node-exporter:
    driver: bridge
