version: "3.8"

services:
  node_exporter:
    image: prom/node-exporter
    hostname: prometheus-node-exporter
    container_name: prometheus-node-exporter
    command:
      - "--path.rootfs=/host"
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
